spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/teste-java
    username: elotech
    password: 'testejava'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true